package main

import "fmt"

// Declares a channel of type int with default value nil
var ch chan int

// <- the pointer operator is used to send and receive values from a channel
// the arrow indicates the direction of data flow

// Send
// Value is being written to the channel
// ch <- v

// Receive
// Value is being recieved from the channel and coppied to the variable
// v = <- ch
// Receive returns new values
// value, ok = <- ch
// ok = true, value is generated by write
// ok = false, value generated by close

func main() {
	fmt.Println("Value of the channel: ", ch)
	fmt.Printf("Type of the channel: %T ", ch)

	// Alternatively
	// make() allocates memory for the channel
	// make() returns a reference for the allocated memory
	// Declare and alocate memory in one statement
	ch2 := make(chan int)
	fmt.Println("\nValue of the channel1: ", ch2)
	fmt.Printf("Type of the channel1: %T ", ch2)
}
